misc: Renamed misc vars

diff --git a/src/gitpl b/src/gitpl
--- a/src/gitpl
+++ b/src/gitpl
@@ -10,30 +10,30 @@
 # License: BSD 3-Clause
 
 if [[ $# -eq 0 ]]; then
-  projects_path=~/Projects
+  projects_dir=~/Projects
 elif [[ $# -eq 1 ]]; then
-  projects_path=$1
+  projects_dir=$1
 else
   echo "Usage: ${0:t} [PATH]..."
   exit
 fi
 
-if [[ ! -d $projects_path ]]; then
-  echo "Directory '${projects_path}' not found! Exiting..."
+if [[ ! -d $projects_dir ]]; then
+  echo "Directory '${projects_dir}' not found! Exiting..."
   exit 1
 fi
 
-echo "Updating all Git repos under '${projects_path/${HOME}/~}'..."
+echo "Updating all Git repos under '${projects_dir/${HOME}/~}'..."
 
-for directory in ${projects_path}/*(N); do
-  if ! git -C $directory rev-parse --is-inside-work-tree &> /dev/null; then
+for dir in ${projects_dir}/*(N); do
+  if ! git -C $dir rev-parse --is-inside-work-tree &> /dev/null; then
     continue
   else
     found_repo=1
   fi
 
-  print -P "\n%B%F{cyan}${directory:t}:%f%b"
-  git -C $directory pull
+  print -P "\n%B%F{cyan}${dir:t}:%f%b"
+  git -C $dir pull
 done
 
 if [[ $found_repo -ne 1 ]]; then
diff --git a/src/gitst b/src/gitst
--- a/src/gitst
+++ b/src/gitst
@@ -19,28 +19,28 @@
 # License: BSD 3-Clause
 
 if [[ $# -eq 0 ]]; then
-  projects_path=~/Projects
+  projects_dir=~/Projects
 elif [[ $# -eq 1 ]]; then
-  projects_path=$1
+  projects_dir=$1
 else
   echo "Usage: ${0:t} [PATH]..."
   exit
 fi
 
-if [[ ! -d $projects_path ]]; then
-  echo "Directory '${projects_path}' not found! Exiting..."
+if [[ ! -d $projects_dir ]]; then
+  echo "Directory '${projects_dir}' not found! Exiting..."
   exit 1
 fi
 
 output=""
 
-for directory in ${projects_path}/*(N); do
-  if ! git -C $directory rev-parse --is-inside-work-tree &> /dev/null; then
+for dir in ${projects_dir}/*(N); do
+  if ! git -C $dir rev-parse --is-inside-work-tree &> /dev/null; then
     continue
   fi
 
-  pushd $directory
-  output="${output}${directory:t}:"
+  pushd $dir
+  output="${output}${dir:t}:"
   branch=$(git branch --show-current 2> /dev/null)
   if [[ -n $(git status --porcelain 2> /dev/null) ]]; then
     output="${output}%B%F{red}${branch}%f%b"
@@ -56,8 +56,8 @@ for directory in ${projects_path}/*(N); do
 done
 
 if [[ -n $output ]]; then
-  print -P "%B%F{cyan}${projects_path:t}:%f%b"
+  print -P "%B%F{cyan}${projects_dir:t}:%f%b"
   print -P $output | column -s ":" -t
 else
-  echo "No Git repos found under '${projects_path/${HOME}/~}'."
+  echo "No Git repos found under '${projects_dir/${HOME}/~}'."
 fi
